canary-test-npm-cache-save-restore

diff --git a/.github/workflows/save-restore.yml b/.github/workflows/save-restore.yml
--- a/.github/workflows/save-restore.yml
+++ b/.github/workflows/save-restore.yml
@@ -1,14 +1,20 @@
-name: npm-cache-restore-save
+name: npm-cache-save-restore
 on:
   push:
     branches:
     - main
+
 jobs:
   build:
     name: Build Test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - uses: actions/cache/save@v3
+        id: cache-save
+        with:
+          path: ${{ github.workspace }}/node_modules
+          key: ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}-${{ github.sha }}
       - uses: actions/cache/restore@v3
         id: cache-restore
         with:
@@ -17,14 +23,8 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-beta-node-${{ hashFiles('**/package-lock.json') }}
             ${{ runner.os }}-beta-node-
-      - name: NPM install
-        shell: bash
+      - name: Fail if cache not found
+        if: steps.cache-restore.outputs.cache-hit != 'true'
         run: |
-          pwd
-          npm install
-      - uses: actions/cache/save@v3
-        if: ${{ steps.cache-restore.outputs.cache-primary-key !=  steps.cache-restore.outputs.cache-matched-key }}
-        id: cache-save
-        with:
-          path: ${{ github.workspace }}/node_modules
-          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
+          echo "Cache miss occurred, hence throwing error."
+          exit 1
